### ISSUE TITLE
No contacts synced for ActiveExchange provider

### ISSUE THREAD

**Issue by scossu** [jobisoft/EAS-4-TbSync#213] opened 2022-12-14 19:17 UTC
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.6.0 on OSX Monterey

## Expected behavior
I should see all my company's contacts on my contact address book.

## Actual behavior
No contacts are shown.

## Steps to reproduce

On a fresh TB install:

- Set up my company's email on Office365 (probably optional)
- Install TBSync and Exchange provider
- In TBSync, add a provider for ActiveExchange
- Select Office365 as the provider option
- Authenticate via OAuth as requested
- Check all the sync checkboxes in the TBSync dialog. Calendars and contacts appear
- Manually sync all items
- Check the calendar: it is showing all events
- Check the contacts: O365 address book is showing but it's empty
- Try to set contacts as read-only and re-sync
- Address book is still empty

**Comment by geg-ck** [comment] 2022-12-15 14:10
Known limitation: https://github.com/jobisoft/TbSync/issues/620.

**Comment by akops76** [comment] 2023-03-09 14:40
Hello, is the project abandoned??

The problem with the contacts has been reported since October 2022 and i haven't found any update about it since then.

Unfortunately without this features TbSync is useless for me.

**Comment by jim-davenport** [comment] 2023-03-09 14:57
He will not answer this question for some reason. I had to give up on Thunderbird. I try so hard to support FOSS. It is becoming too much of a chore. The new Outlook Preview seems to give me much of what I need and I don't have to struggle to keep it operational.

**Comment by jobisoft** [comment] 2023-03-10 09:16
Hi, I am doing this in my free time, which is becoming less and less. I said I will try to bring back the feature, but I cannot give you an ETA. I will close this as a dupe of https://github.com/jobisoft/TbSync/issues/620

**Closed by jobisoft** 2023-03-10 09:16 UTC
