### ISSUE TITLE
Failed to add Office365 account using OAuth due to access request

### ISSUE THREAD

**Issue by plaskowski** [jobisoft/EAS-4-TbSync#96] opened 2020-01-09 15:27 UTC
## Your environment

TbSync version: 2.9
EAS-4-TbSync version: 1.9
Thunderbird version: 68.2.2

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I can add Office365 account.

## Actual behavior
I get stuck on "Add account" dialog using "MS Office 365" option.

## Steps to reproduce
- open TbSync settings
- click "Add new account > Exchange ActiveSync"
- pick "MS Office 365" option
- enter name and email (the email is in custom domain of my company)
- click "Add account"
- a OAuth windows pops up
- I login with my credentials
- I enter MFA code from SMS
- a "send access request" page is shown
- I click to send the request
- the OAuth pop-up dissapear
- The "Add account" dialog shows error (see screenshot in comment)
- My admin accept the request and I receive e-mail notification about it
- I start the process over again but I causes sending another request

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by plaskowski** [comment] 2020-01-09 15:50
![image](https://user-images.githubusercontent.com/1999603/72082221-1d21ea80-3300-11ea-8786-d1fb4d3dd099.png)
![image](https://user-images.githubusercontent.com/1999603/72082234-21e69e80-3300-11ea-8ac0-041b9da0906a.png)
![image](https://user-images.githubusercontent.com/1999603/72082241-2448f880-3300-11ea-8040-100e3aeec125.png)

**Comment by jobisoft** [comment] 2020-01-09 17:24
Did you get the email notification, that your admin accepted? Is ther anything usefull in it? A link or something?

**Comment by plaskowski** [comment] 2020-01-10 08:50
Hi,
I did but nothing interesting there. I've also turned on the full TbSync
debugging but also there was nothing interesting there.
[image: image.png]

**Comment by plaskowski** [comment] 2020-01-10 09:30
Hi,
I've found something like this in the OAuth pop-up page footer, maybe that would allow to continue the flow after manual approval:
> Request Id: 7e203762-769a-47b4-9815-92b0cf021700
> Correlation Id: 69616883-57f6-4e99-9741-811f486d1ea2
> Timestamp: 2020-01-10T09:07:32Z

**Comment by jobisoft** [comment] 2020-01-17 17:41
I tried to find something regardings this is the OAUTH2 docs but I failed. Is your admin pro FOSS? Would he grant me a test account so I can try this on my own and inspect what is going on?

**Comment by plaskowski** [comment] 2020-01-17 18:15
I'm afraid it won't be possible.
Still big Thank You for looking at this.
I went for generating app password and thankfully it worked.

Bests,
Piotr

pt., 17.01.2020, 18:41 użytkownik John Bieling <notifications@github.com>
napisał:

**Comment by jobisoft** [comment] 2020-01-17 19:56
Ok, I leave this issue open and maybe we can fix this in the future.

**Comment by plaskowski** [comment] 2020-01-18 09:57
Sure.
You could send me some guide how to debug this (I'm a programmer) if you
have one at hand.

Bests,
Piotr

pt., 17.01.2020, 20:56 użytkownik John Bieling <notifications@github.com>
napisał:

**Comment by dheuts** [comment] 2020-02-25 19:51
I got stuck in the "Admin approval needed" window. The admin of my company granted the Admin consent, but the application keeps popping up with "Admin approval needed". 

If the admin tries to grant admin consent via the Azure AD portal an error message appears: 

> AADSTS650056: Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, The admin has not consented in the tenant. Or, Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant. Client app ID: 2980deeb-7460-4723-864a-f9b0f10cd992.

**Comment by y1mwolce** [comment] 2020-03-04 07:46
It seems similar to the problem in DavMail: "the application has not been approved". See Jan Pilz's answer in https://sourceforge.net/p/davmail/bugs/702/
It would be nice if the 2 parameters mentioned there could be overridden.

**Comment by jobisoft** [comment] 2020-03-04 11:26
@y1mwolce : What parameters?

**Comment by y1mwolce** [comment] 2020-03-04 13:11
davmail.oauth.clientId and davmail.oauth.redirectUri

**Comment by jobisoft** [comment] 2020-03-04 13:16
I am not allowed to use a client id which was not registered for me. I will check with that redirect URI.

**Comment by y1mwolce** [comment] 2020-03-04 13:23
1. Sometimes it is inevitable to use the clientid of another application - esp. then admins do not want to add a new one. 
2. Give the user the configuration option, don't set it in stone.

**Comment by jobisoft** [comment] 2020-03-04 13:41
No really, I will violate terms of use, do not want to go there.

**Comment by y1mwolce** [comment] 2020-03-04 14:37
How would you violate them, if you have a default, that the user can override?
Your choice, in any case.

**Comment by jobisoft** [comment] 2020-03-12 15:59
This boils down to me getting an account, where this happens, so I can debug this. I have access to 3 different tenants and cannot reproduce this.

**Comment by SaskaTune** [comment] 2020-07-06 18:13
I have also been experiencing this problem using your plugin. We've seen similar behavior with the gmail app.  Perhaps this post may shed some light on the cause: https://support.google.com/mail/thread/25018514?hl=en

**Comment by jobisoft** [comment] 2020-07-06 19:45
Interesting link. Could you give this version a spin?
[EAS-4-TbSync_1.14.1.xpi](https://github.com/jobisoft/EAS-4-TbSync/files/4880926/EAS-4-TbSync.zip)

**Comment by SaskaTune** [comment] 2020-07-06 20:08
Authentication seems to be working with that version.  No looping requests for approval.

**Comment by jobisoft** [comment] 2020-07-06 20:24
https://github.com/jobisoft/EAS-4-TbSync/commit/8fa1d6b5f704d32b44579c0fa26152483c644c6c

Available via beta release channel.
https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

Will not send it out to stable/ATN, because addon review queue is slow due to TB78 updates. Will be part of first release for TB78.

Please use beta and report issues. Thanks for testing.

**Comment by jobisoft** [comment] 2020-07-16 22:25
This is now part of the new beta for TB78. Beta for TB68 have been discontinued.

**Comment by jobisoft** [comment] 2020-07-21 06:19
TbSync is now officially available for TB78 and it includes this fix.

**Closed by jobisoft** 2020-07-21 06:19 UTC
Labels: help needed
