### ISSUE TITLE
Include other calendars

### ISSUE THREAD

**Issue by elaratain** [jobisoft/EAS-4-TbSync#131] opened 2020-09-16 09:05 UTC
Hi,

your plug-in works perfectly. However, it would be nice, if you could include calendars listed under "Other Calendars", usually those are calendars shared by other people.

Regards

**Comment by jobisoft** [comment] 2020-09-20 22:01
Duplicate of https://github.com/jobisoft/EAS-4-TbSync/issues/132

**Closed by jobisoft** 2020-09-20 22:01 UTC
