### ISSUE TITLE
TBSync keeps in a loop when syncing Exchange items that have been locally accepted

### ISSUE THREAD

**Issue by vlietland** [jobisoft/EAS-4-TbSync#111] opened 2020-03-02 21:33 UTC
TbSync version: 1.7.2 - 2.1.1
Thunderbird version: 60-68

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
... Syncing should work as normal

## Actual behavior
... TBSync keeps in a loop waiting and processing

## Steps to reproduce
1. Install latest version TB
2. Install latest version TBSync and Provider for Exchange
3. Sync Exchange calendar from Exchange
4. Receive an agenda item from a friend
5. Accept the item in Thunderbird
6. Sync
7. Keeps running in a loop

## added comments:
I have reproduced it on another system, installed from scratch
Happens as of version 0.7.7 (did not go further in time) until the latest version 2.1.1. 
Only happens if locally accepted items, not with items accepted in the online version and read-only received.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
-- Done

**Comment by jobisoft** [comment] 2020-03-28 17:58
I cannot reproduce this with the latest beta: https://tbsync.jobisoft.de

What happens here is, that I get the pending event synced into my calendar and if I accept the email belonging to that invite, Thunderbird puts a new accepted event into my calendar (so I have both) and if sync that, the server removes that accepted event again. So after the sync the email is back to "please accept" and the added accepted event by Thunderbird is removed again.

This is the current state, as I have not implemented meeting support. You need to accept events via the webinterface.

However the loop you saw is of course not good and should not happen. Is it still there with beta?

**Comment by vlietland** [comment] 2020-03-30 18:54
I just did some more checking and noticed indeed the following behavior:
a. pending event requests from other mail addresses are correctly synced 
from Exchange to Lightning (result = ok)
b. sent out event requests from my account to others are correctly 
synced from Lightning to Exchange (result = ok)
c. sent out responses (Accept, Tentative, Decline) in LIghtning are 
stored in Lightning and not correctly synced with Exchange. In that case 
the error log reports an error that one element has not been accepted 
due to a collision. The collision is likely the event that is already in 
the Exchange calender (the not accepted one). When I remove the accepted 
event the error is gone. But then I end up without the event of course 
which is not in conformity with the actual situation because I have let 
the recipient know that I accepted the event (result = error)
d. sent out responses (Accept, Decline) from my Thunderbird mail are 
stored in Lightning and from there not synced with Exchange. In that 
case the TBSync ends up in a loop. When I remove the accepted event the 
error is gone. But then I end up without the event of course which is 
not in conformity with the actual situation because I have let the 
recipient know that I accepted the event.
e. The imported ics file has the same behavior. It also ends up in a 
loop (result = error)

Have you also tried to import the ics file that I send you? That should 
cause the loop.


What is the reason that event responses have not been implemented in the 
adapter?

**Comment by KIAOman2020** [comment] 2020-08-20 09:29
I have different behavior with TbSync & Exchange ActiveSync as below:

a. pending event requests from other mail addresses are correctly synced
from Exchange to Lightning (result = ok)
b. sent out event requests from my account to others are correctly
synced from Lightning to Exchange (result = ok)
c. sent out responses (Accept, Tentative, Decline) in Lightning are
stored in Lightning and not correctly synced with Exchange. Accepted invitations will not show list of attendees in Exchange and will show like it was not accepted yet. Also after next Tbsync synchronization interval invitation will be shown in light blue color with note "You haven't yet responded to this invitation" .

TbSync v.2.16 with Exchange Activesync
TB 78.1.1

**Comment by jobisoft** [comment] 2022-09-24 09:46
I will close this in favour of one of the other issues related to invites, which are not properly handled.

**Comment by jobisoft** [comment] 2022-09-24 09:46
I will close this in favour of one of the other issues related to invites, which are not properly handled.

**Closed by jobisoft** 2022-09-24 09:46 UTC
Labels: bug, need info, meeting stuff postponed
