### ISSUE TITLE
Two Microsoft Office 365 accounts configured, only one can sync

### ISSUE THREAD

**Issue by mcihelka** [jobisoft/EAS-4-TbSync#249] opened 2023-10-05 07:53 UTC
## Your environment

TbSync version: 4.7 (5 October 2023)
EAS-4-TbSync version: 4.7 (5 October 2023)
Thunderbird version: 115.3.1
OS: Arch Linux x86-64

## Expected behavior

If two Microsoft Office 365 accounts are configured in TbSync, you should be able to sync one and then the other without error.

## Actual behavior

In a new Thunderbird session, when I sync one account (either), it syncs perfectly. Then, when I try to sync the other account, it fails with an error status:

Sometimes `Communication error (HTTP status 503)`, sometimes `status.Settings.111`.

**Nutshell:** In a new Thunderbird session, the *first* account I sync, *whichever one I choose*, works for the entire session and the other account cannot sync for the entire session.

## Steps to reproduce

1. Configure two Microsoft Office 365 accounts in TbSync (you may need to restart Thunderbird between configuring the first and second account)
2. Restart Thunderbird
3. In TbSync, choose any account to sync first, it should work
4. Try to sync the other account, it should fail
5. Restart Thunderbird and try steps 3 and 4 again, but flip the order in which you sync the accounts

I've been able to replicate this issue 100% on two different PCs over the last couple of days.

**Comment by jobisoft** [comment] 2023-12-02 23:53
Looks like a session cookie issue. Will check.

**Comment by RobMahn** [comment] 2024-02-05 14:27
I referenced this issue in "TBsyn not conecting to server #259" to clarify the reason for connectivity problems.

Now that Microsoft is stopping the use of app passwords, more people that use multiple accounts will have this problem.

**Comment by ColeBantam** [comment] 2024-02-08 09:41
Can't wait to see that issue fixed, because I had to install "Mail and Calendar" to have my private Calendar visible on PC ... Hopefully I can bring back this calendar into Thunderbird soon :)

**Comment by jobisoft** [comment] 2024-04-01 14:48
Dupe of https://github.com/jobisoft/TbSync/issues/713

**Closed by jobisoft** 2024-04-01 14:48 UTC
Labels: bug

**Comment by jobisoft** [comment] 2024-08-19 18:54
Can you check the beta for TB128?
https://github.com/jobisoft/EAS-4-TbSync/issues/267#issuecomment-2297181031
