### ISSUE TITLE
Allow login and email address domains to be different

### ISSUE THREAD

**Issue by erwdavid** [jobisoft/EAS-4-TbSync#21] opened 2018-11-09 10:50 UTC
## Your environment

TbSync version: 0.7.17
Thunderbird version:
60.0.3
[ x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
In the company I work for I have address edavid@domain1.com, but login to exchange is on AD domain domain2.com

Expected behavior is to be able to specify different login username and email address (in Advanced settings). It could also be interesting to access calendar of another person (even only free/busy)

## Actual behavior
email address is used as username for login, and it does not work everywhere

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment] 2018-11-09 10:59
Can you elaborate this more? 

What stops you from using the correct login username from domain2.com? 

The email address you enter in the setup wizard  is used for autodiscover (and if set up correctly by your admin, it should return the correct username from domain2 even if an email from domain1 was used). But if that does not work for either of your adresses (domain1 and domain2) you can still setup the account manually.

What should be changed?

Thanks for your feedback,
John

**Comment by jobisoft** [comment] 2018-11-09 20:45
@erwdavid Still with me?

**Comment by erwdavid** [comment] 2018-11-09 21:12
Hi, when using the login edavid@domain2.com no synchronization happens, and I have no way to specify my email address is edavid@domain1.com (and users of this exchange server use several different email domains, thus no evident mapping).

In the manual account definition. There is one only field for username and email address. If I use the email address, authentication fails. If I use the usernae with AD domain, I get no calendar.

**Comment by erwdavid** [comment] 2018-11-09 21:32
I'll ask on monday.

**Comment by jobisoft** [comment] 2018-11-16 09:42
This looks like a duplicate of https://github.com/jobisoft/EAS-4-TbSync/issues/22#issuecomment-439334341

**Closed by jobisoft** 2018-11-16 09:42 UTC
